# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0008_auto_20160106_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is published'),
        ),
    ]
